# Build stage
FROM node:18-alpine as build

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --max-old-space-size=4096

# Run stage
FROM node:18-alpine as run

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/.env .
COPY package*.json ./
RUN npm install --only=production && \
    rm package*.json

EXPOSE 8000

CMD ["node", "dist/main.js"]